Fedora build
open-eid/libdigidocpp pull request #441
Opened 2021-11-04 09:20 UTC by eidins

Replacement for https://github.com/open-eid/libdigidocpp/pull/410 with rebase and conflict resolved

2021-11-04 09:36 UTC, eidins commented
```
cmake ..
make
make package
```

All work and the RPM installs fine.

2021-11-09 11:33 UTC, metsma commented on CMakeLists.txt
> +set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/local" "/usr/local/etc" "/usr/share/man" "/usr/share/man/man1" "/usr/lib64/pkgconfig")
Package should not install anything into /usr/local

2021-11-11 10:50 UTC, metsma requested changes

2021-11-11 10:50 UTC, metsma commented on .github/workflows/build.yml
> +    runs-on: fedora-latest
ubuntu-latest, Github action does not have fedora-latest

2021-11-16 11:02 UTC, metsma commented
If you plan build digidoc4-client you probably need also save the artifacts. If not we can merge

2021-11-18 18:11 UTC, metsma approved these changes

2021-11-18 18:12 UTC, metsma commented
There are some issues with the artefacts
"Build on Fedora to fedora:33
No files were found with the provided path: libdigidocpp*.rpm. No artifacts will be uploaded."

2021-11-18 18:13 UTC, metsma commented on .github/workflows/build.yml
> +        path: libdigidocpp*.rpm
Build on Fedora to fedora:33
No files were found with the provided path: libdigidocpp*.rpm. No artifacts will be uploaded.

2021-11-18 18:15 UTC, metsma commented on .github/workflows/build.yml
> +        path: libdigidocpp*.rpm
path: build/libdigidocpp*.rpm ??

2021-11-19 06:35 UTC, metsma commented
Lets see if this also adds config files to correct place
set(CPACK_RPM_SOURCE_PKG_BUILD_PARAMS -DCMAKE_INSTALL_SYSCONFDIR=/etc)

2021-11-21 10:52 UTC, metsma requested changes

2021-11-21 10:52 UTC, metsma commented on .github/workflows/build.yml
> +        cmake ..
```suggestion
        cmake -DCMAKE_INSTALL_SYSCONFDIR=/etc ..
```

2021-11-21 10:52 UTC, metsma commented on CMakeLists.txt
> +set(CPACK_RPM_SOURCE_PKG_BUILD_PARAMS -DCMAKE_INSTALL_SYSCONFDIR=/etc)
```suggestion
```
Seems like this did not help

2021-11-21 13:10 UTC, metsma approved these changes

2021-11-24 06:08 UTC, merged