Get EVP_MD_CTX from EVP_Digest(3) to fix LibreSSL build
open-eid/libdigidocpp pull request #550
Opened 2023-08-14 13:25 UTC by klemensn

Just include the header instead of redefining the type,
otherwise it fails to build on OpenBSD:

```
/usr/include/openssl/ossl_typ.h:103:30: error: type alias redefinition with different types ('struct env_md_ctx_st' vs 'struct evp_md_ctx_st')
typedef struct env_md_ctx_st EVP_MD_CTX;
                             ^
/usr/ports/pobj/libdigidocpp-3.16.0/libdigidocpp-3.16.0/src/crypto/Digest.h:59:7: note: previous definition is here
using EVP_MD_CTX = struct evp_md_ctx_st;
```

Signed-off-by: Klemens Nanni <kn@openbsd.org>

2023-08-15 06:45 UTC, metsma requested changes
Don't expose openssl headers in headers. It will introduce build time dependencies to third party usages

2023-08-15 07:42 UTC, klemensn commented
> Don't expose openssl headers in headers. It will introduce build time dependencies to third party usages

OK, this should work, then.

2023-08-24 07:12 UTC, metsma approved these changes

2023-08-24 07:13 UTC, metsma commented
Can you please rebase on master. There are fixes for window build issues

2023-08-31 00:11 UTC, merged